### ISSUE TITLE
Rename `DONATION_BENEFACTOR` / remove hardcoded value

### ISSUE THREAD

**Issue by lsaether** [ethereum-alarm-clock/ethereum-alarm-clock#104]
Right now the donation benefactor is hardcoded into the contracts. We can rename this variable to something more apt, such as "affiliate" or "partner" address. We need to also change this value to to be directed to a multisig wallet, since right now I just have it aimed at a regular address.

**Comment by pipermerriam** [comment]
Maybe even just `fee_address`.  I was originally averse to the term *fee* but I think it's appropriate and easier for people to understand.  Also, it will be hidden from the user in many cases since it will be the UX which institutes the fee.
