### ISSUE TITLE
EIP standardization 

### ISSUE THREAD

**Issue by lsaether** [ethereum-alarm-clock/ethereum-alarm-clock#120]
EIPs are a good way to bring a lot of smart eyes on a discussion. We may want to engage the EIP community about forming a standard around the Ethereum Alarm Clock scheduling contracts and procedure. This would open up the way for developers to feel comfortable using the contracts more freely. A big theme of the EAC is the necessity of having a standard so I think it may be good to begin the process of forming an official standard.

**Comment by pipermerriam** [comment]
I think this would be a very good idea.  Just an EIP which defined the Scheduler and Request API formally would go a long way towards this being a reliable foundation that others can build upon.

**Comment by kosecki123** [comment]
I think this actually ends up with [ERC 1228](https://github.com/ethereum/EIPs/issues/1228)
