### ISSUE TITLE
Sender unable to refund with has fallback fn with more than 2300 gas needed

### ISSUE THREAD

**Issue by kosecki123** [ethereum-alarm-clock/ethereum-alarm-clock#133]
Unable to send back remaining ETH if fallback function consumes more than 2300gas, because remaining ETH is send using msg.sender.send(). This potentially locks remaining funds on the scheduled smart contract.

In order to handle this case @pipermerriam proposed to add this API:
```
function refundOwner() {}  \\ sends refund to owner address
function refundOwner(address to) only_owner {} \\ only callable by owner, sends to the `to` address
```

**Comment by pipermerriam** [comment]
Alternate solution would be to have these *pull* APIs not use `addr.send()` and instead use `addr.call.value(...)()` to send the value with all available gas.  Since these APIs are pull based, this should be fine.
