### ISSUE TITLE
How to handle gas prices for scheduled transactions?

### ISSUE THREAD

**Issue by mudgen** [ethereum-alarm-clock/ethereum-alarm-clock#203]
It is unknown what the price for gas will be in the future.  So how can you capture the gas price to use for a future transaction?  How do you handle this?

**Comment by kosecki123** [comment]
I've wrote a piece on how EAC is handling gas prices, please take a look here https://blog.chronologic.network/how-to-picking-the-right-gas-price-for-scheduled-transactions-94e740328ec9
