### ISSUE TITLE
Funds stuck in delegated contract due to low gas fees. 

### ISSUE THREAD

**Issue by dahifi** [ethereum-alarm-clock/ethereum-alarm-clock#204]
So my normie brother wound up using Crypto.com to send funds and accidentally scheduled the tx. He only used 20 gwei for the gas, so of course the funds are still sitting there. 

His tx ID is 0x72a4a8786f61c6623fd1730ec031b53e2a709b4c6a1dc24332dbf88bf7781663. I'm trying to figure out how to call the funds on the TimestampScheduler contract, but can't tell what's the right call. 

I'm willing to pay the gas myself, or reimburse someone to do it for us.

**Comment by thiagobtcsoul** [comment]
We recommend that you cancel the transaction via the UI using the owner's account.
That being said, the smart contract does allow canceling with other accounts. To do that, you would call the function in line 1229 here https://etherscan.io/address/0xff5c4b7ec93dd70b862af027bb7f3d9900002c4d#code but for contract at https://etherscan.io/address/0x710b77241ed61ea9ec64b76bff4bdd835268d306. You may use this function in the dapp for reference: https://github.com/chronologic/eth-alarm-clock-dapp/blob/develop/app/components/TransactionScanner/TransactionDetails.js#L113

**Comment by dahifi** [comment]
Thanks, but calling that RequestsLib function is a bit beyond me. We'll do it using the owner account on the UI. 

Thanks!
