### ISSUE TITLE
The scheduler address seems not to be correct

### ISSUE THREAD

**Issue by philipodonnell** [ethereum-alarm-clock/ethereum-alarm-clock#59]
Has this project been abandoned? I tried to install a client and finally hit an error 

```
Error: The scheduler address seems to not be correct. Using 0x6c8f2a135f6ed072de4503bd7c4999a1a17f824b. You may need to specify the address using --address if you are running the client against a test network.
```

**Comment by philipodonnell** [comment]
The contract does appear to exist. https://etherscan.io/address/0x6c8f2a135f6ed072de4503bd7c4999a1a17f824b

Perhaps my configuration cannot find it? I did hit quite a few issues following the instructions in the docs.

**Comment by pipermerriam** [comment]
This project has not been abandoned :)

Can you expand on what issues you ran into.  Code you ran.  Errors you received.  Transactions you sent?

**Comment by pipermerriam** [comment]
@philipodonnell is it possible that your client has not fully synced the blockchain?  Based on your original pasted output I'm guessing that your chain is still syncing.

**Comment by philipodonnell** [comment]
Ah, I see. That would make sense. Is there a way to check that the geth has finished syncing? I am tailing the log files but all I see is "imported 1 block" every few seconds, I assume those are new blocks.

On the errors during installation, off the top of my head there were a number of dependency issues with cffi and fflr and pip. Also I had to symlink to the geth.ipc file because the defaults were looking for it in ~/.ethereum/geth but the directory I found it in after following the tutorials was in the /data/ethereum folders.

**Comment by philipodonnell** [comment]
I used the latest Ubuntu 15.04 from here: https://virtualboxes.org/images/ubuntu/#ubuntu1504

**Comment by pipermerriam** [comment]
I'm going to close this issue.  Feel free to re-open when/if you have any specific issue.

I am aware that there are parts of this code that are fragile.  I'm currently working on a lot of upstream changes in the `populus` and `web3.py` codebases that once done, will propogate down into this project and ideally improve the state of things.

But by all means, let me know about any issues you run into and I'm happy to help you get them working.

**Comment by lsaether** [comment]
Closing old issue
