### ISSUE TITLE
DelayedPayment example on site unclear / outdated

### ISSUE THREAD

**Issue by gnidan** [ethereum-alarm-clock/ethereum-alarm-clock#69]
Hi,

In trying to test this out, I'm running into some problems that appear to be related to Solidity changes in the last few months.

The [Quick-start DelayedPayment example](http://docs.ethereum-alarm-clock.com/en/latest/quickstart.html#scheduling-your-first-transaction) is not compiling for Solidity >= 0.4.0. Furthermore, Parity UI seems to discourage payable constructors. Not aware of historical reasons / changes, but it appears that changes to the Solidity language make the quick-start example outdated.

Error in recent versions of Solidity:
```
Member "value" not found or not visible after argument-dependent lookup in function (address,bytes memory,uint8,uint256[3] memory) external returns (address) - did you forget the "payable" modifier?
        scheduler.scheduleTransaction.value(0.1 ether)(
        ^---------------------------------^
```

Please advise, thank you!

**Comment by pipermerriam** [comment]
It may be a bit before I can get to this but I appreciate you reporting it.

**Comment by Marduuk** [comment]
Hey guys!
I ran into the same problem, @gnidan did you figured how to do that maybe?

**Comment by lsaether** [comment]
the delayed payment example is now up to date
