### ISSUE TITLE
Reboot the service

### ISSUE THREAD

**Issue by pipermerriam** [ethereum-alarm-clock/ethereum-alarm-clock#82]
The service is dormant right now and in need of a full reboot to become a useful tool for the Ethereum community.  In order to reboot, the following tasks need to be done.

* Update contracts to work with a modern (`0.4.x`) version of solidity
* Remove stack depth checks from execution contracts as the EVM no longer has hard stack limit.
* Update test suite to pass
* Update execution client

This is likely multiple weeks worth of work.  If anyone were to decide to take this update on, I would happily work out a deal for partial ownership of the project.

**Comment by hacxman** [comment]
hi, i've already invested some time (and money :D) to get it (current state, whatever it means) running. it was a rough fight. so, i'd love to help reboot the service.

**Comment by pipermerriam** [comment]
@hacxman can you provide a bit more context?  Is it possible for you to open a pull request?

Currently, there is work in progress to contract an individual to work on this full time to get it back off the ground.   I can't go into more detail right now but I'd hate to waste the work you've done.  If you'd like to reach out to me on gitter we can talk more on the subject.

**Comment by postables** [comment]
I would be willing to help.
I know Python 2+3, Solidity, little bit of Golang, Bash Scripting, and solid experience as a Linux SysAdmin.

**Comment by pipermerriam** [comment]
❗️   https://blog.chronologic.network/ethereum-alarm-clock-beta-release-0-9-0-ce7bc27dbb6f
