### ISSUE TITLE
Unable to run the client

### ISSUE THREAD

**Issue by golyalpha** [ethereum-alarm-clock/ethereum-alarm-clock#83]
Here's the traceback:
render@renderBox:~# eth_alarm
Traceback (most recent call last):
  File "/usr/local/bin/eth_alarm", line 7, in <module>
    from eth_alarm_client.cli import main
  File "/usr/local/lib/python2.7/dist-packages/eth_alarm_client/__init__.py", line 2, in <module>
    from .call_contract import CallContract  # NOQA
  File "/usr/local/lib/python2.7/dist-packages/eth_alarm_client/call_contract.py", line 12, in <module>
    from .contracts import (
  File "/usr/local/lib/python2.7/dist-packages/eth_alarm_client/contracts.py", line 4, in <module>
    from populus.contracts import Contract
ImportError: cannot import name Contract

**Comment by golyalpha** [comment]
I followed the instructions from the old repo (some of which I've written myself), since there are none on this repo.

**Comment by pipermerriam** [comment]
See https://github.com/pipermerriam/ethereum-alarm-clock/issues/82 for the current status of this service.

If you want to try and run the client you're going to need to do some manual pinning of requirements.  For everything you find in the requirements here https://github.com/pipermerriam/ethereum-alarm-clock/blob/master/setup.py you should install exactly that version as opposed to `>=` that version.  This will need to be done all the way down the requirements.

**Comment by postables** [comment]
I would be willing to help.
I know Python 2+3, Solidity, little bit of Golang, Bash Scripting, and solid experience as a Linux SysAdmin

**Comment by lsaether** [comment]
closing old issue
