### ISSUE TITLE
Clarify which testnet is used

### ISSUE THREAD

**Issue by fvictorio** [ethereum-alarm-clock/ethereum-alarm-clock#87]
Hi, I think the [source section](http://www.ethereum-alarm-clock.com/source/v0.7.0/) should indicate which testnet is used. I searched for that address in [Ropsten](https://ropsten.etherscan.io/address/0x26416b12610d26fd31d227456e9009270574038f), [Kovan](https://kovan.etherscan.io/address/0x26416b12610d26fd31d227456e9009270574038f) and [Rinkeby](https://rinkeby.etherscan.io/address/0x26416b12610d26fd31d227456e9009270574038f) but neither of those has anything at that address.

**Comment by kosecki123** [comment]
Currently, the 0.9.3 is deployed both on Kovan and Ropsten. Check the main page https://github.com/ethereum-alarm-clock/ethereum-alarm-clock or https://github.com/ethereum-alarm-clock/ethereum-alarm-clock/commit/bb64d33730bbf29cedcb34418d162efdfbbefcf5
