### ISSUE TITLE
Implementers Guide

### ISSUE THREAD

**Issue by pipermerriam** [ethereum-alarm-clock/ethereum-alarm-clock#93]
Migrated from https://github.com/ethereum-alarm-clock/eac.js/issues/9

I think one thing that would make adoption by wallets and whatnot smoother would be an implementers guide.  All of the information is probably already present in the docs, but something targeted directly at someone who's implementing a graphical interface on top of the protocol would go a long way to help get metamask/mew/mist onboard.

**Comment by lsaether** [comment]
closing since this is no longer needed
