### ISSUE TITLE
Bug in Alarm Clock example?

### ISSUE THREAD

**Issue by ColdDevil** [ethereum-alarm-clock/ethereum-alarm-clock#96]
I'm referring to line 49 in here:
https://github.com/ethereum-alarm-clock/ethereum-alarm-clock/blob/master/contracts/_examples/DelayedPayment.sol#L49

Maybe I'm confusing something, but shouldn't this line be `require(getNow() > lockedUntil)` ? Isn't the idea that `payout()` should only be possible *after* the block number stated in `lockedUntil` has been reached?

**Comment by lsaether** [comment]
You are correct, in the example `payout()` is only allowed to be called beginning at the `lockedUntil` time. Thank you for pointing that out. 

Fixed in commit b96053d3149fa6cdcf6dcc5838f84da7a6ddfa44
